In [9]:
import pandas as pd

In [11]:
import numpy as np

In [59]:
miles = pd.DataFrame({'farthest_run_mi': [50, 62, np.nan, 100, 26,np.nan, 31, 50]})

In [61]:
miles

farthest_run_mi
0             50.0
1             62.0
2              NaN
3            100.0
4             26.0
5              NaN
6             31.0
7             50.0

In [63]:
miles.isna().sum()

farthest_run_mi    2
dtype: int64

In [65]:
from sklearn.impute import SimpleImputer

In [67]:
imp_mean = SimpleImputer(strategy='mean')

In [69]:
imp_mean.fit_transform(miles)

array([[ 50.        ],
       [ 62.        ],
       [ 53.16666667],
       [100.        ],
       [ 26.        ],
       [ 53.16666667],
       [ 31.        ],
       [ 50.        ]])

In [71]:
imp_median = SimpleImputer(strategy='median')

In [73]:
imp_median.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 50.],
       [ 31.],
       [ 50.]])

In [75]:
imp_mod = SimpleImputer(strategy='most_frequent')

In [77]:
imp_mod.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 50.],
       [ 31.],
       [ 50.]])

In [79]:
imp_constant=SimpleImputer(strategy='constant',fill_value=13)

In [81]:
imp_constant.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 13.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [83]:
names = pd.DataFrame({'Names': ['Khaled','amr', np.nan,'ahmed','ali', 'mohemed','mahmoud','eslem']})

In [85]:
names

Names
0   Khaled
1      amr
2      NaN
3    ahmed
4      ali
5  mohemed
6  mahmoud
7    eslem

In [87]:
imp_constant = SimpleImputer(strategy = 'constant',fill_value='alaa')

In [89]:
imp_constant.fit_transform(names)

array([['Khaled'],
       ['amr'],
       ['alaa'],
       ['ahmed'],
       ['ali'],
       ['mohemed'],
       ['mahmoud'],
       ['eslem']], dtype=object)

In [96]:
imp_mean_marke=SimpleImputer(strategy='mean',add_indicator=True)

In [98]:
imp_mean_marke.fit_transform(miles)

array([[ 50.        ,   0.        ],
       [ 62.        ,   0.        ],
       [ 53.16666667,   1.        ],
       [100.        ,   0.        ],
       [ 26.        ,   0.        ],
       [ 53.16666667,   1.        ],
       [ 31.        ,   0.        ],
       [ 50.        ,   0.        ]])

In [106]:
Work = pd.DataFrame({'Names': ['Khaled','amr', np.nan,'ahmed','ali', 'mohemed','mahmoud','eslem'],
                     'farthest_run_mi': [50, 62, np.nan, 100, 26,np.nan, 31, 50]})

In [108]:
Work

Names  farthest_run_mi
0   Khaled             50.0
1      amr             62.0
2      NaN              NaN
3    ahmed            100.0
4      ali             26.0
5  mohemed              NaN
6  mahmoud             31.0
7    eslem             50.0

In [112]:
from sklearn.compose import make_column_transformer

In [146]:
ct   = make_column_transformer(
       (imp_constant,['Names']),
      (imp_mean,['farthest_run_mi']),
      remainder='drop'    
)


In [148]:
ct.set_output(transform='pandas')

ColumnTransformer(transformers=[('simpleimputer-1',
                                 SimpleImputer(fill_value='alaa',
                                               strategy='constant'),
                                 ['Names']),
                                ('simpleimputer-2', SimpleImputer(),
                                 ['farthest_run_mi'])])

In [152]:
Work_pandas =ct.fit_transform(Work)

In [154]:
Work_pandas

simpleimputer-1__Names  simpleimputer-2__farthest_run_mi
0                 Khaled                         50.000000
1                    amr                         62.000000
2                   alaa                         53.166667
3                  ahmed                        100.000000
4                    ali                         26.000000
5                mohemed                         53.166667
6                mahmoud                         31.000000
7                  eslem                         50.000000